config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :agents, except: :delete
  resources :patients, except: :delete
  resources :professionals, except: :delete
  resources :cid10s, only: :index

  root to: 'patients#index'
end

app/models/professional.rb
# frozen_string_literal: true

class Professional < ApplicationRecord
  enum function: ['Psicólogo(a)', 'Psiquiatra', 'Enfermeiro(a)', 'Serviços Auxiliares']

  validates :name, presence: true
  validates :function, presence: true
  validates :email, uniqueness: true
  validates :phone, uniqueness: true, case_sensitive: false

  belongs_to :cnes
end

app/controllers/professionals_controller.rb
# frozen_string_literal: true

class ProfessionalsController < ApplicationController
  before_action :set_professional, only: %i[edit show update]

  def new
    @professional = Professional.new
  end

  def create
    @professional = Professional.new(professional_params)

    respond_to do |format|
      if @professional.save
        format.html { redirect_to @professional, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @professional.update(professional_params)
        format.html { redirect_to @professional, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def show; end

  def index
    @q = Professional.ransack(params[:q])
    @professionals = @q.result.page params[:page]
  end

  private

  def professional_params
    params.permit(:name, :function, :email, :phone, :address, :cnes_id)
  end

  def set_professional
    @professional = Professional.find(params[:id])
  end
end

app/views/professionals/_form.html.erb
<h4 class="text-center mt-4 mb-2">Adicionar Funcionário</h4>

<%= form_for (@professional) do |f| %>
    <%= render 'shared/error_messages', object: @professional if @professional.errors.any? %>

    <div class="container shadow rounded mt-3 mb-2">

        <div class="text-secondary pt-3"><h6><strong>Informações Básicas</strong></h6></div>
        <hr class="mb-3 border"/>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :function, 'Cargo' %>
                <%= f.select :function, options_for_select(Professional.functions.map { |key, value| [key.humanize, key] }, selected: @professional.function), 
                {include_blank: 'Selecione...'}, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :name, 'Nome' %>
                <%= f.text_field :name, class: 'form-control', placeholder: 'Digite o nome completo' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :email, 'E-mail' %>
                <%= f.text_field :email, class: 'form-control', placeholder: 'Digite o email' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :address, 'Endereço' %>
                <%= f.text_field :address, class: 'form-control', placeholder: 'Digite o endereço' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :phone, 'Fone' %>
                <%= f.text_field :phone, class: 'form-control', placeholder: 'Digite o telefone (somente números)' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :cnes_id, 'Unidade' %>
                <%= f.collection_select(:cnes_id, Cnes.all, :id, :unity, {include_blank: 'Selecione...'}, class: 'form-control') %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center pt-2 pb-2">
            <div class="col-7">
                <%= link_to 'Cancelar', professionals_path, class: 'btn btn-secondary shadow-sm', title: 'Voltar' %>
                <%= f.submit 'Salvar', class: 'btn btn-primary shadow-sm ml-2', title: 'Registrar novo funcionário' %>
            </div>
        </div>
    </div>
<% end %>

app/views/professionals/_search_form.html.erb
<%= search_form_for @q do |f| %>
    <div class="row justify-content-end">
        <div class="form-group col-2">
            <%= f.label "" %>
            <%= f.collection_select(:cnes_unity_cont, Cnes.all.order(:unity), :unity, :unity, {include_blank: 'Unidade'}, class: 'form-control') %>
        </div>

        <div class="form-group col-2">
            <%= f.label "" %>
            <%= f.select :function_eq, options_for_select(Professional.functions), {include_blank: 'Cargo'}, class: 'form-control' %>
        </div>

        <div class="form-group col-3">
            <%= f.label "" %>
            <%= f.search_field :name_cont, class: 'form-control', placeholder: 'Nome do funcionário' %>
        </div> 

        <div class="form-group pt-4 mr-3">
            <%= f.submit 'Buscar', class: 'btn btn-primary shadow-sm'  %>
        </div>
    </div>
<% end %>

app/views/professionals/edit.html.erb
<%= render 'form' %>

app/views/professionals/index.html.erb
<title>Sistema CAPS - Funcionários</title>

<h4 class="text-center mt-4 mb-2">Lista de Funcionários</h4>

<div class="container shadow rounded pb-3">
    <%= render 'search_form' %>

    <table class="table table-hover mt-2">
        <thead class="">
            <tr class="font-weight-bold">
                <td>Nome</td>
                <td>Cargo</td>
                <td>Unidade</td>
                <td colspan="2">
            </tr>
        </thead>

        <tbody>
            <% @professionals.each do |professional| %>
                <tr>
                    <td><%= link_to professional.name, professional %></td>
                    <td><%= professional.function %>
                     <td><%= professional.cnes.unity %>
                    <td><%= link_to '', edit_professional_path(professional), class: 'btn btn-outline-primary fas fa-edit fa-sm', title: 'Editar funcionário' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <div class="row justify-content-around">
        <div class="col mt-2">
            <%= page_entries_info @professionals, entry_name: 'funcionários' %>
        </div>
        <div class="col align-self-end">
            <%= paginate @professionals %>
        </div>
    </div>
</div>

app/views/professionals/new.html.erb
<%= render 'form' %>

app/views/professionals/show.html.erb
<h4 class="text-center mt-4 mb-2">Informações de Funcionário</h4>

<div class="container shadow rounded mt-2">
    <div class="text-secondary text-center pt-3"><h6><strong>FICHA DO FUNCIONÁRIO</strong></h6></div>
    <hr class="mb-2 border">

    <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>Nome</strong></div>
            <div class="text-center"><%= @professional.name %></div>
        </div>
    </div>

    <hr class="mb-2">

      <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>Função</strong></div>
            <div class="text-center"><%= @professional.function %></div>
        </div>
    </div>

    <hr class="mb-2">

    <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>CNES - Unidade</strong></div>
            <div class="text-center"><%= @professional.cnes.unity%></div>
        </div>
    </div>

     <hr class="mb-2">

    <div class="row justify-content-center mb-2">
         <div class="col">
            <div class="text-center"><strong>E-mail</strong></div>
            <div class="text-center"><% if @professional.email.nil? %><div class="mb-4"></div><% else %><%= @professional.email %><% end %></div>
        </div>
    </div>

    <hr class="mb-2">

    <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>Fone</strong></div>
            <div class="text-center"><% if @professional.phone.nil? %><div class="mb-4"></div><% else %><%= @professional.phone %><% end %></div>
        </div>
    </div>

    <hr class="mb-2">

    <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>Endereço</strong></div>
            <div class="text-center"><% if @professional.address.nil? %><div class="mb-4"></div><% else %><%= @professional.address %><% end %></div>
        </div>
    </div>

    <hr class="mb-3">

    <div class="text-center pb-3">
        <%= link_to ('Voltar'), professionals_path, class: 'btn btn-dark shadow-sm', title: 'Voltar para tabela de funcionários' %>
        <%= link_to ('Editar'), edit_professional_path(@professional), class: 'btn btn-primary shadow-sm', title: 'Editar ficha do funcionário' %>
    </div>
</div>