config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :agents, except: :delete
  resources :patients, except: :delete
  resources :professionals, except: :delete
  resources :cid10s, only: :index

  root to: 'patients#index'
end

app/models/agent.rb
# frozen_string_literal: true

class Agent < ApplicationRecord
  validates :name, presence: true
  validates :email, :phone, uniqueness: true

  belongs_to :cnes
  has_many :patients
end

app/controllers/agents_controller.rb
# frozen_string_literal: true

class AgentsController < ApplicationController
  before_action :set_agent, only: %i[edit show update]

  def new
    @agent = Agent.new
  end

  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def show; end

  def index
    @q = Agent.ransack(params[:q])
    @agents = @q.result.page params[:page]
  end

  private

  def agent_params
    params.permit(:name, :email, :phone, :address, :cnes_id)
  end

  def set_agent
    @agent = Agent.find(params[:id])
  end
end

app/helpers/agents_helper.rb
# frozen_string_literal: true

module AgentsHelper
end

app/views/agents/_form.html.erb
<h4 class="text-center mt-4 mb-2">Adicionar Agente</h4>

<%= form_for (@agent) do |f| %>
    <%= render 'shared/error_messages', object: @agent if @agent.errors.any? %>

    <div class="container shadow rounded mt-3 mb-2">

        <div class="text-secondary pt-3"><h6><strong>Informações Básicas</strong></h6></div>
        <hr class="mb-3 border"/>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :name, 'Nome' %>
                <%= f.text_field :name, class: 'form-control', placeholder: 'Digite o nome completo' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :email, 'E-mail' %>
                <%= f.text_field :email, class: 'form-control', placeholder: 'Digite o email' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :address, 'Endereço' %>
                <%= f.text_field :address, class: 'form-control', placeholder: 'Digite o endereço' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :phone, 'Fone' %>
                <%= f.text_field :phone, class: 'form-control', placeholder: 'Digite o telefone (somente números)' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :cnes_id, 'Unidade' %>
                <%= f.collection_select(:cnes_id, Cnes.all, :id, :unity, {include_blank: 'Selecione...'}, class: 'form-control') %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center pt-2 pb-2">
            <div class="col-7">
                <%= link_to 'Cancelar', agents_path, class: 'btn btn-secondary shadow-sm', title: 'Voltar' %>
                <%= f.submit 'Salvar', class: 'btn btn-primary shadow-sm ml-2', title: 'Registrar novo agente' %>
            </div>
        </div>
    </div>
<% end %>

app/views/agents/_search_form.html.erb
<%= search_form_for @q do |f| %>
    <div class="row justify-content-end">
        <div class="form-group col-2">
            <%= f.label "" %>
            <%= f.collection_select(:cnes_unity_cont, Cnes.all.order(:unity), :unity, :unity, {include_blank: 'Unidade'}, class: 'form-control') %>
        </div>

        <div class="form-group col-3">
            <%= f.label "" %>
            <%= f.search_field :name_cont, class: 'form-control', placeholder: 'Nome do agente' %>
        </div> 

        <div class="form-group pt-4 mr-3">
            <%= f.submit 'Buscar', class: 'btn btn-primary shadow-sm'  %>
        </div>
    </div>
<% end %>

app/views/agents/edit.html.erb
<%= render 'form' %>

app/views/agents/index.html.erb
<title>Sistema CAPS - Agentes</title>

<h4 class="text-center mt-4 mb-2">Lista de Agentes</h4>

<div class="container shadow rounded pb-3">
    <%= render 'search_form' %>

    <table class="table table-hover mt-2">
        <thead class="">
            <tr class="font-weight-bold">
                <td>Nome</td>
                <td>Unidade</td>
                <td colspan="2">
            </tr>
        </thead>

        <tbody>
            <% @agents.each do |agent| %>
                <tr>
                    <td><%= link_to agent.name, agent %></td>
                    <td><%= agent.cnes.unity %>
                    <td><%= link_to '', edit_agent_path(agent), class: 'btn btn-outline-primary fas fa-edit fa-sm', title: 'Editar agente' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <div class="row justify-content-around">
        <div class="col mt-2">
            <%= page_entries_info @agents, entry_name: 'agentes' %>
        </div>
        <div class="col align-self-end">
            <%= paginate @agents %>
        </div>
    </div>
</div>

app/views/agents/new.html.erb
<%= render 'form' %>

app/views/agents/show.html.erb
<h4 class="text-center mt-4 mb-2">Informações de Agente</h4>

<div class="container shadow rounded mt-2">
    <div class="text-secondary text-center pt-3"><h6><strong>FICHA DO AGENTE</strong></h6></div>
    <hr class="mb-2 border">

    <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>Nome</strong></div>
            <div class="text-center"><%= @agent.name %></div>
        </div>
    </div>

    <hr class="mb-2">

    <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>CNES - Unidade</strong></div>
            <div class="text-center"><%= @agent.cnes.unity%></div>
        </div>
    </div>

     <hr class="mb-2">

    <div class="row justify-content-center mb-2">
         <div class="col">
            <div class="text-center"><strong>E-mail</strong></div>
            <div class="text-center"><% if @agent.email.nil? %><div class="mb-4"></div><% else %><%= @agent.email %><% end %></div>
        </div>
    </div>

    <hr class="mb-2">

    <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>Fone</strong></div>
            <div class="text-center"><% if @agent.phone.nil? %><div class="mb-4"></div><% else %><%= @agent.phone %><% end %></div>
        </div>
    </div>

    <hr class="mb-2">

    <div class="row justify-content-center mb-2">
        <div class="col">
            <div class="text-center"><strong>Endereço</strong></div>
            <div class="text-center"><% if @agent.address.nil? %><div class="mb-4"></div><% else %><%= @agent.address %><% end %></div>
        </div>
    </div>

    <hr class="mb-3">

    <div class="text-center pb-3">
        <%= link_to ('Voltar'), agents_path, class: 'btn btn-dark shadow-sm', title: 'Voltar para tabela de agentes' %>
        <%= link_to ('Editar'), edit_agent_path(@agent), class: 'btn btn-primary shadow-sm', title: 'Editar ficha do agente' %>
    </div>
</div>