config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :agents, except: :delete
  resources :patients, except: :delete
  resources :professionals, except: :delete
  resources :cid10s, only: :index

  root to: 'patients#index'
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  before_validation :calculate_age, on: %i[create update]

  enum status: %w[Ativo Inativo]
  enum gender: %w[Masculino Feminino Outro]
  enum marital_status: ['Solteiro(a)', 'Casado(a)', 'Divorciado(a)', 'Viúvo(a)', 'Separado(a)']

  validates :medical_record_number, presence: true, uniqueness: true
  validates :name, presence: true
  validates :gender, presence: true
  validates :birthdate, presence: true
  validates :admission_date, presence: true
  validates :sus_card, presence: true, uniqueness: true, length: { is: 15 }, case_sensitive: false
  validates :cpf, presence: true, uniqueness: true, length: { is: 11 }, case_sensitive: false
  validates :rg, presence: true, uniqueness: true, length: { in: 9..11 }, case_sensitive: false
  validates :adress, presence: true
  validates :phone, uniqueness: true
  validates :status, presence: true

  belongs_to :cnes
  belongs_to :agent
  has_and_belongs_to_many :cid10s
  has_and_belongs_to_many :psychoative_substances

  private

  def calculate_age
    self.age = ((Time.zone.now - birthdate.to_time) / 1.year.seconds).floor
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  before_action :set_patient, only: %i[edit show update destroy]

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def show; end

  def index
    @q = Patient.ransack(params[:q])
    @patients = @q.result.page params[:page]
  end

  private

  def patient_params
    params.permit(:medical_record_number, :name, :gender, :birthdate, :admission_date, :age, :marital_status, :mother_name, :father_name,
                  :sus_card, :cpf, :rg, :county, :adress, :phone, :cnes_id, :status, :agent_id, psychoative_substance_ids: [], cid10_ids: [])
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end
end

app/helpers/patients_helper.rb
# frozen_string_literal: true

module PatientsHelper
end

app/views/patients/_form.html.erb
<h4 class="text-center mt-4 mb-2">Adicionar Paciente</h4>

<%= form_for (@patient) do |f| %>
    <%= render 'shared/error_messages', object: @patient if @patient.errors.any? %>

    <div class="container shadow rounded mt-3 mb-2">

        <div class="text-secondary pt-3"><h6><strong>Informações Básicas</strong></h6></div>
        <hr class="mb-3 border"/>

         <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :medical_record_number, 'Número de Prontuário' %>
                <%= f.text_field :medical_record_number, class: 'form-control', placeholder: 'Digite o número de prontuário' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :name, 'Nome' %>
                <%= f.text_field :name, class: 'form-control', placeholder: 'Digite o nome completo' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center justify-content-center">
            <div class="col-7">
                <%= f.label :gender, 'Gênero' %>
                <%= f.select :gender, options_for_select(Patient.genders.map { |key, value| [key.humanize, key] }, selected: @patient.gender), 
                {include_blank: 'Selecione...'}, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :marital_status, 'Estado Civil' %>
                <%= f.select :marital_status, options_for_select(Patient.marital_statuses.map { |key, value| [key.humanize, key] }, selected: @patient.marital_status), 
                {include_blank: 'Selecione...'}, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :birthdate, 'Data de Nascimento' %>
                <%= f.date_field :birthdate, class: 'form-control' %>
            </div>
        </div>


        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :admission_date, 'Data de Admissão' %>
                <%= f.date_field :admission_date, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :father_name, 'Nome do Pai' %>
                <%= f.text_field :father_name, class: 'form-control', placeholder: 'Digite o nome do pai completo' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :mother_name, 'Nome da Mãe' %>
                <%= f.text_field :mother_name, class: 'form-control', placeholder: 'Digite o nome da mãe completo' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :cnes_id, 'Unidade' %>
                <%= f.collection_select(:cnes_id, Cnes.all, :id, :unity, {include_blank: 'Selecione...'}, class: 'form-control') %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :agent_id, 'ACS' %>
                <%= f.collection_select(:agent_id, Agent.all, :id, :name, {include_blank: 'Selecione...'}, class: 'form-control') %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :rg, 'RG' %>
                <%= f.text_field :rg, class: 'form-control', placeholder: 'Digite o RG (somente números)'%>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :cpf, 'CPF' %>
                <%= f.text_field :cpf, class: 'form-control', placeholder: 'Digite o CPF (somente números)'%>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :sus_card, 'Cartão SUS' %>
                <%= f.text_field :sus_card, class: 'form-control', placeholder: 'Digite o cartão SUS (somente números)' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :adress, 'Endereço' %>
                <%= f.text_field :adress, class: 'form-control', placeholder: 'Digite o endereço' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :phone, 'Fone' %>
                <%= f.text_field :phone, class: 'form-control', placeholder: 'Digite o telefone (somente números)' %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :psychoative_substance_ids, 'Substâncias Psicoativas' %>
                <%= f.collection_select(:psychoative_substance_ids, PsychoativeSubstance.all, :id, :name, 
                {include_blank: "Pressione 'Ctrl' para seleção múltipla..."}, {multiple: true, class: 'form-control'}) %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :cid10_ids, 'CID-1O' %>
                <%= f.collection_select(:cid10_ids, Cid10.all, :id, :code, 
                {include_blank: "Pressione 'Ctrl' para seleção múltipla..."}, {multiple: true, class: 'form-control'}) %>
            </div>
        </div>

        <div class="form-group form-row justify-content-center">
            <div class="col-7">
                <%= f.label :status, 'Status' %><br/>
                <div class="form-check-inline">
                    <%= f.radio_button :status, 'Ativo', class: 'form-check-input' %>
                    <%= f.label :status, 'Ativo', value: 0, class: 'form-check-label' %>
                    <%= f.radio_button :status, 'Inativo', class: 'form-check-input ml-2' %>
                    <%= f.label :status, 'Inativo', value: 1, class: 'form-check-label' %>
                </div>
            </div>
        </div>

        <div class="form-group form-row justify-content-center pt-2 pb-2">
            <div class="col-7">
                <%= link_to 'Cancelar', patients_path, class: 'btn btn-secondary shadow-sm', title: 'Voltar' %>
                <%= f.submit 'Salvar', class: 'btn btn-primary shadow-sm ml-2', title: 'Registrar novo paciente' %>
            </div>
        </div>
    </div>
<% end %>

app/views/patients/_search_form.html.erb
<%= search_form_for @q do |f| %>
    <div class="row justify-content-end">
        <div class="form-group col-2">
            <%= f.label "" %>
            <%= f.collection_select(:cnes_unity_cont, Cnes.all.order(:unity), :unity, :unity, {include_blank: 'Unidade'}, class: 'form-control') %>
        </div>

         <div class="form-group col-2">
            <%= f.label "" %>
            <%= f.collection_select(:psychoative_substances_name_cont, PsychoativeSubstance.all.order(:name), 
            :name, :name, {include_blank: 'Substâncias'}, class:'form-control') %>
        </div>

        <div class="form-group col-2">
            <%= f.label "" %>
            <%= f.select :status_eq, options_for_select(Patient.statuses), {include_blank: 'Status'}, class: 'form-control' %>
        </div>

        <div class="form-group col-2">
            <%= f.label "" %>
            <%= f.search_field :cid10s_code_cont, class: 'form-control', placeholder: 'Código CID-10' %>
        </div>

        <div class="form-group col-3">
            <%= f.label "" %>
            <%= f.search_field :name_cont, class: 'form-control', placeholder: 'Nome do paciente' %>
        </div> 

        <div class="form-group pt-4 mr-3">
            <%= f.submit 'Buscar', class: 'btn btn-primary shadow-sm'  %>
        </div>
    </div>
<% end %>

app/views/patients/index.html.erb
<title>Sistema CAPS - Pacientes</title>

<h4 class="text-center mt-4 mb-2">Lista de Pacientes</h4>

<div class="container shadow rounded pb-3">
    <%= render 'search_form' %>

    <table class="table table-hover mt-2">
        <thead class="">
            <tr class="font-weight-bold">
                <td>N.º de Prontuário</td>
                <td>Nome</td>
                <td>Unidade</td>
                <td>Status</td>
                <td colspan="2">
            </tr>
        </thead>

        <tbody>
            <% @patients.each do |patient| %>
                <tr>
                    <td><%= patient.medical_record_number %></td>
                    <td><%= link_to patient.name, patient %></td>
                    <td><%= patient.cnes.unity %>
                    <td><%= patient.status %>
                    <td><%= link_to '', edit_patient_path(patient), class: 'btn btn-outline-primary fas fa-edit fa-sm', title: 'Editar paciente' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <div class="row justify-content-around">
        <div class="col mt-2">
            <%= page_entries_info @patients, entry_name: 'pacientes' %>
        </div>
        <div class="col align-self-end">
            <%= paginate @patients %>
        </div>
    </div>
</div>

app/views/patients/show.html.erb
<h4 class="text-center mt-4 mb-2">Informações do Paciente</h4>

<div class="container shadow rounded">
    <div class="text-secondary text-center pt-3"><h6><strong>FICHA DO PACIENTE N.º <%= @patient.medical_record_number %></strong></h6></div>
    <hr class="mb-2 border"/>

    <div class="row justify-content-center mb-2">
        <div class="col-4">
            <div class="text-center"><strong>Nome</strong></div>
            <div class="text-center"><%= @patient.name %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>Gênero</strong></div>
            <div class="text-center"><%= @patient.gender %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>Estado Civil</strong></div>
            <div class="text-center"><% if @patient.marital_status.nil? %><div class="mb-4"></div><% else %><%= @patient.marital_status %><% end %></div>
        </div>
    </div>

    <hr class="mb-2"/>

    <div class="row justify-content-center mb-2">
        <div class="col-4">
            <div class="text-center"><strong>Data de Nascimento</strong></div>
            <div class="text-center"><%= @patient.birthdate %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>Data de Admissão</strong></div>
            <div class="text-center"><%= @patient.admission_date %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>Idade</strong></div>
            <div class="text-center"><%= @patient.age %> anos</div>
        </div>
    </div>

    <hr class="mb-2"/>

    <div class="row justify-content-center mb-2">
        <div class="col-4">
            <div class="text-center"><strong>Nome do Pai</strong></div>
            <div class="text-center"><% if @patient.father_name.nil? %><div class="mb-4"></div><% else %><%= @patient.father_name %><% end %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>Nome da Mãe</strong></div>
            <div class="text-center"><% if @patient.mother_name.nil? %><div class="mb-4"></div><% else %><%= @patient.mother_name %><% end %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>ACS</strong></div>
            <div class="text-center"><%= @patient.agent.name %></div>
        </div>
    </div>

    <hr class="mb-2"/>

    <div class="row justify-content-center mb-2">
        <div class="col-4">
            <div class="text-center"><strong>RG</strong></div>
            <div class="text-center"><%= @patient.rg %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>CPF</strong></div>
            <div class="text-center"><%= @patient.cpf %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>Cartão SUS</strong></div>
            <div class="text-center"><%= @patient.sus_card %></div>
        </div>
    </div>

    <hr class="mb-2"/>

    <div class="row justify-content-center mb-2">
        <div class="col-4">
            <div class="text-center"><strong>Endereço</strong></div>
            <div class="text-center"><%= @patient.adress %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>Fone</strong></div>
            <div class="text-center"><% if @patient.phone.nil? %><div class="mb-4"></div><% else %><%= @patient.phone %><% end %></div>
        </div>
        <div class="col-4">
            <div class="text-center"><strong>CNES - Unidade</strong></div>
            <div class="text-center"><%= @patient.cnes.unity %></div>
        </div>
    </div>

    <hr class="mb-2"/>

    <div class="row justify-content-center mb-2">
        <div class="col-4">
            <div class="text-center"><strong>Substâncias Psicoativas</strong></div>
            <div class="text-center"><%= @patient.psychoative_substances.map(&:name).join('; ') %></div>
        </div>
         <div class="col">
            <div class="text-center"><strong>CID-10</strong></div>
            <div class="text-center"><%= @patient.cid10s.map(&:code).join('; ') %></div> 
        </div>
         <div class="col-4">
            <div class="text-center"><strong>Status</strong></div>
            <div class="text-center"><%= @patient.status %></div>
        </div>
    </div>

    <hr class="mb-3"/>

    <div class="text-center pb-3">
        <%= link_to ('Voltar'), patients_path, class: 'btn btn-dark shadow-sm', title: 'Voltar para tabela de pacientes' %>
        <%= link_to ('Editar'), edit_patient_path(@patient), class: 'btn btn-primary shadow-sm', title: 'Editar ficha do paciente' %>
    </div>
</div>